In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("data/items.parquet")
df_user = pd.read_parquet("data/train.parquet")
df.head(10)

,item_id,title,description,features,category,brand,price,image_url
0,B085RX192V,Crocs Women’s Freesail Clog,Elegant floral graphics croslite foam construc...,100% Croslite Imported Ethylene Vinyl Acetate ...,AMAZON FASHION,Crocs,49.95,https://m.media-amazon.com/images/I/31ntcDSaCr...
1,B078J3FZ12,BEARPAW Women's Boshie Multiple Colors | Women...,,Imported Rubber sole Imported Rubber Sole Cow ...,AMAZON FASHION,BEARPAW,54.96,https://m.media-amazon.com/images/I/31Ly1kzrr4...
2,B07VKPPCNP,Scrubs for Women Workwear Professionals V-Neck...,,"63% Polyester, 34% Cotton, 3% Spandex Imported...",AMAZON FASHION,Cherokee,21.99,https://m.media-amazon.com/images/I/31P6tzEWBy...
3,B07BZCPRWC,"Free to Live 3 Pack Womens Long, Loose Fitting...",,"95% Rayon, 5% Spandex Made in USA Pull On clos...",AMAZON FASHION,Free to Live,43.95,https://m.media-amazon.com/images/I/31fCkEUsY9...
4,B07H253XTD,Ginjang Women Winter Snow Boots Warm Ankle Boo...,,Rubber sole >>Keep Warm : Fine fluffy wool cov...,AMAZON FASHION,Ginjang,NaN,https://m.media-amazon.com/images/I/41eE6Qmf7W...
5,B0BHDBDL7H,"Hanes Women's Crewneck Sweatshirt, EcoSmart Fl...",Stay comfy on the go with our unbelievably sof...,"50% Cotton, 50% Polyester Imported Pull On clo...",AMAZON FASHION,Hanes,NaN,https://m.media-amazon.com/images/I/41fKrUfh2T...
6,B09R1PZC6K,Holipick Two Piece Swim Dress for Women Swimdr...,,"85% Polyester, 15% Spandex Spring closure Two ...",AMAZON FASHION,Holipick,29.98,https://m.media-amazon.com/images/I/41Eot2SGuA...
7,B098Y68NJV,New Balance Women's Sneaker,We stand for something bigger than sneakers. W...,"50% Mesh, 50% Synthetic Imported Rubber sole T...",AMAZON FASHION,New Balance,NaN,https://m.media-amazon.com/images/I/311mWNdjNs...
8,B07QTVKNNQ,Dickies Men's Dri-tech Moisture Control Crew S...,Dickies dri-tech comfort Pairs crew with wicki...,"72% Cotton, 26% Polyester, 2% Spandex Imported...",AMAZON FASHION,Dickies,20.70,https://m.media-amazon.com/images/I/41kfiXvAAo...
9,B07BNS1JCF,DEARCASE Women's Long Sleeve Maxi Dress Crewne...,,"95% Rayon, 5% Spandex Imported Pull On closure...",AMAZON FASHION,DEARCASE,34.99,https://m.media-amazon.com/images/I/41j5xyy0Kk...

In [3]:
df_user.head(10)

,user_id,item_id,rating,timestamp,verified_purchase
0,AE22CUYKCASNE3FV6MTCG7AIQFSA,B019VM3CPW,5.0,1470875333000,True
1,AE22CUYKCASNE3FV6MTCG7AIQFSA,B079GB72Q1,5.0,1537139381412,True
2,AE22CUYKCASNE3FV6MTCG7AIQFSA,B014L0J1PE,5.0,1537139459544,True
3,AE22CUYKCASNE3FV6MTCG7AIQFSA,B09ZQ5G8D7,5.0,1554554871099,True
4,AE22CUYKCASNE3FV6MTCG7AIQFSA,B0BGH8XQF6,5.0,1563065459823,True
5,AE22CUYKCASNE3FV6MTCG7AIQFSA,B083R4YZCJ,5.0,1563477940958,True
6,AE22CUYKCASNE3FV6MTCG7AIQFSA,B08KVDRG5V,5.0,1594002546503,True
7,AE22CUYKCASNE3FV6MTCG7AIQFSA,B078T87H8D,5.0,1614364470457,True
8,AE22E26NYX7FQGYKAGJY4OUORTMA,B004HI2E6Y,4.0,1386016464000,True
9,AE22E26NYX7FQGYKAGJY4OUORTMA,B0922DBSLN,5.0,1507907860367,True

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31368 entries, 0 to 31367
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   item_id      31368 non-null  object
 1   title        31368 non-null  object
 2   description  31368 non-null  object
 3   features     31368 non-null  object
 4   category     31368 non-null  object
 5   brand        31306 non-null  object
 6   price        26566 non-null  float64
 7   image_url    31361 non-null  object
dtypes: float64(1), object(7)
memory usage: 1.9+ MB